"use strict";

const toMarkdown = require("to-markdown");
const strip = require("striptags");

/**
 * Strip every tag except "a" and "br"
 *
 * @param {string} input - Input string
 * @returns {string}
 */
function stripTags(input) {
  return strip(input, ["a", "br"]);
}

/**
 * Strip the bracket syntax generated by the API
 *
 * @param {string} input - Input string
 * @returns {string}
 */
function stripBrackets(input) {
  return input.replace(/<\/a>( \[[a-zA-Z.-]*\])/g, match => "</a>");
}

/**
 * Trim every line
 *
 * @param {string} input - Input string
 * @returns {string}
 */
function trimLines(input) {
  return input.split("\n").map(line => line.trim()).join("\n") + "\n";
}

/**
 * Convert output from the API (back) to Markdown
 *
 * @param {string} input - Input string
 * @returns {string}
 */
module.exports = function(input) {
  let output = input;

  output = stripTags(output);
  output = stripBrackets(output);

  output = toMarkdown(output);
  output = trimLines(output);

  return output;
};
