"use strict";

var toMarkdown = require("to-markdown");
var strip = require("js-striphtml");

/**
 * Strip every tag except "a" and "br"
 *
 * @param {string} input - Input string
 * @returns {string}
 */
function stripTags(input) {
  return strip.stripTags(input, ["a", "br"]);
}

/**
 * Strip the bracket syntax generated by the API
 *
 * @param {string} input - Input string
 * @returns {string}
 */
function stripBrackets(input) {
  return input.replace(/<\/a>( \[[a-zA-Z.-]*\])/g, function(match) {
    return "</a>";
  });
}

/**
 * Trim every line
 *
 * @param {string} input - Input string
 * @returns {string}
 */
function trimLines(input) {
  return (
    input
      .split("\n")
      .map(function(line) {
        return line.trim();
      })
      .join("\n") + "\n"
  );
}

/**
 * Convert output from the API (back) to Markdown
 *
 * @param {string} input - Input string
 * @returns {string}
 */
module.exports = function(input) {
  return trimLines(toMarkdown(stripBrackets(stripTags(input))));
};
